
CREATE DATABASE IF NOT EXISTS `employees` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `employees`;

CREATE TABLE USER (
    ID   INTEGER,
    NAME VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE EMPLOYEE (
    ID       INTEGER      NOT NULL,
    NAME     VARCHAR(100) NOT NULL,
    BIRTHDAY DATE         NOT NULL,
    CPF      DECIMAL(11)  NOT NULL,
    ACTIVE   CHAR(1)      NOT NULL DEFAULT 'S',
    EMAIL    VARCHAR(100),
    PHONE    VARCHAR(20),
    ADDRESS  VARCHAR(100),

    USER_CREATED INTEGER,
    CREATED_AT   DATE,
    USER_UPDATED INTEGER,
    UPDATED_AT   DATE,

    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LANGUAGE (
    ID    INTEGER      NOT NULL,
    NAME  CHAR(4)      NOT NULL,
    DESCR VARCHAR(100) NOT NULL,

    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RESUME (
    EMPLOYEE_ID INTEGER NOT NULL,
    LANGUAGE_ID INTEGER NOT NULL,
    RESUME      TEXT,
    EXPERIENCE  TEXT,
    EDUCATION   TEXT,

    USER_CREATED INTEGER,
    CREATED_AT   DATE,
    USER_UPDATED INTEGER,
    UPDATED_AT   DATE,

    PRIMARY KEY (EMPLOYEE_ID, LANGUAGE_ID),

    FOREIGN KEY (LANGUAGE_ID)
        REFERENCES LANGUAGE (ID)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    
    FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE (ID)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
